[build]
  base = "client"
  publish = "dist"
  command = "if [ -f pnpm-lock.yaml ]; then pnpm install && pnpm run build; elif [ -f yarn.lock ]; then yarn install && yarn build; else npm ci && npm run build; fi"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
